apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  app.conf: |
      server {
          listen       80;
          server_name  app.cloudageskill.com;

          #uncomment for logs
          #access_log  logs/host.access.log  main;

          location /app1 {
              proxy_set_header   X-Real-IP        $remote_addr;
              proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
              proxy_set_header   Host             $host;
              rewrite ^/app1(.*) /$1 break;
              proxy_pass http://192.168.49.2:30503; # make sure port matches open port in node app
          }

          location /app2 {
              proxy_set_header   X-Real-IP        $remote_addr;
              proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
              proxy_set_header   Host             $host;
              rewrite ^/app2(.*) /$1 break;
              proxy_pass http://192.168.49.2:30907; # make sure port matches open port in node app
          }
      }
    
  