apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: "TCP"
    # Port accessible inside cluster
    port: 80
    # Port to forward to inside the pod
    targetPort: 80
    # Port accessible outside cluster
    nodePort: 30985
  type: LoadBalancer
  externalIPs:
  - 192.168.49.2
